import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, ArrowRight, MessageCircle } from 'lucide-react';
import { whatsapp } from '@/lib/site';
import type { ReactNode } from 'react';

export function Wordmark({footer=false}:{footer?:boolean}) { return <span className={`wordmark luxe-wordmark ${footer?'wordmark-footer':''}`}><span>The Luxe Vault<span className="logo-dot">.</span></span><small>P R E - L O V E D  L U X U R Y</small></span>; }
export function Eyebrow({children}:{children:ReactNode}) {return <p className="eyebrow"><span />{children}</p>;}
export function Photo({src,alt,className='',priority=false,sizes='(max-width: 768px) 100vw, 50vw'}:{src:string;alt:string;className?:string;priority?:boolean;sizes?:string}) {return <div className={`photo ${className}`}><Image src={src} alt={alt} fill sizes={sizes} priority={priority}/></div>;}
export function TextLink({href,children}:{href:string;children:ReactNode}) {return <Link className="text-link" href={href}>{children}<ArrowUpRight size={17}/></Link>;}
export function ContactButton({children='WhatsApp 免費估價',message,className=''}:{children?:ReactNode;message?:string;className?:string}) {return <a href={whatsapp(message)} className={`button ${className}`} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={17}/></a>;}
export function PageIntro({eyebrow,title,description}:{eyebrow:string;title:string;description:string}) {return <header className="page-intro wrap"><Eyebrow>{eyebrow}</Eyebrow><div className="page-intro-grid"><h1>{title}</h1><p className="body-copy">{description}</p></div></header>;}
export function SectionHead({eyebrow,title,href,label}:{eyebrow:string;title:string;href?:string;label?:string}) {return <div className="section-head"><div><Eyebrow>{eyebrow}</Eyebrow><p className="cta-heading">{title}</p></div>{href&&<TextLink href={href}>{label||'探索更多'}</TextLink>}</div>;}
export function CtaBand() {return <section className="cta-band"><div className="wrap cta-inner"><div><Eyebrow>YOUR NEXT CHAPTER</Eyebrow><p className="cta-heading">讓喜愛，繼續流轉。</p><p>從一張照片開始，發現您珍藏的下一種可能。</p></div><ContactButton className="button-light"/></div></section>;}
export function Footer() {return <footer className="site-footer"><div className="wrap"><div className="footer-grid"><div><Link href="/" aria-label="The Luxe Vault 首頁"><Wordmark footer/></Link><p className="footer-tagline">PRE-LOVED. RE-LOVED.</p><p className="muted text-sm leading-7">讓經典延續，讓美好循環。<br/>香港名牌手袋收購及鑑定。</p></div><div><p className="footer-heading">探索 The Luxe Vault</p><Link href="/brands">收購品牌</Link><Link href="/case">交易案例</Link><Link href="/blogs">The Luxe Vault 風格誌</Link></div><div><p className="footer-heading">為您而設</p><Link href="/takeoverauth">收購及鑑定</Link><Link href="/howtosell">如何出售</Link><Link href="/faq">常見問題</Link></div><div><p className="footer-heading">LET’S TALK</p><a className="footer-contact" href={whatsapp()} target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/> WhatsApp 聯絡我們 <ArrowUpRight size={15}/></a><p className="muted text-xs leading-6 mt-4">一對一諮詢・預約制交收<br/>Hong Kong</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} The Luxe Vault. All rights reserved.</span><span>所有商標均屬各品牌所有，The Luxe Vault 並非其授權代理。</span><Link href="#top" aria-label="返回頁首">BACK TO TOP <ArrowRight size={13} className="-rotate-90"/></Link></div></div></footer>;}
